---
title: "CodeBook.Rmd for Getting & Cleaning Data Course Project"
author: "Nic"
date: "9/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data

The purpose of this project is to collect, work with and clean a data set that can be used for later analysis. The data is from the UCI Machine Learning Repository: Human Activity Recognition and Smart Phone. Detailed information can be read [here](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones), and data can be downloaded [here](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip).

## Cleaning Up Data

### #1: Merging the training and the test sets to create one data set.

Data was first downloaded from the link provided by the course instructors, and read in with names corresponding to the source files. Test and training data were merged based on variable type (Features, Activity, Subject). The final data set was merged and saved as "dataMerge".

### 2: Extracting only the measurements on the mean and standard deviation for each measurement.

Created a variable "theNamesData" that was a subset of the entire dataset to include only the measurements on the mean and standard deviation for each measurement. Concatenated this data with the rest and saved it as "filteredData".

### 3: Using descriptive activity names to name the activities in the data set.

The integer labels for column 'Activity' were replaced by the true activity labels / names. This was done by factorising the 'Activity' column in "filteredData".

### 4: Appropriately labelling the data set with descriptive variable names.

Parts of the column names in "filteredData" were substituted based on what they represented in the experiment, whereby:  
  - t is replaced with time  
  - f is replaced with frequency  
  - Acc is replaced with Accelerometer  
  - Gyro is replaced with Gyroscope  
  - Mag is replaced with Magnitude  

#### 5: Finally, create a second, independent tidy data set with the average of each variable for each activity and each subject.

"filteredData" from the end of step #4 was grouped first by Activity, then Subject, and summarised by mean. Do note that the dply package was applied to achieve this.

## Variables

### Descriptive Variables

- Subject: ID, from 1-30  
- Activity: Name of activity, also denoted by numbers 1-6  

### Measurements

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

A set of signals were used to estimate variables of the feature vector for each pattern; '-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.  

The set of variables that were estimated from these signals are:     

mean(): Mean value  
std(): Standard deviation  
mad(): Median absolute deviation   
max(): Largest value in array  
min(): Smallest value in array  
sma(): Signal magnitude area  
energy(): Energy measure. Sum of the squares divided by the number of values.   
iqr(): Interquartile range   
entropy(): Signal entropy  
arCoeff(): Autorregresion coefficients with Burg order equal to 4  
correlation(): correlation coefficient between two signals  
maxInds(): index of the frequency component with largest magnitude  
meanFreq(): Weighted average of the frequency components to obtain a mean frequency  
skewness(): skewness of the frequency domain signal   
kurtosis(): kurtosis of the frequency domain signal   
bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.  
angle(): Angle between to vectors.  

Additional vectors obtained by averaging the signals in a signal window sample.  

The complete list of variables of each feature vector is available in 'features.txt'
